name: Generate Sitemap

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to generate sitemap for'
        required: true
        type: string

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git config
      run: |
        git config --global user.name 'jphabs'
        git config --global user.email 'jpbermoy@gmail.com'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Generate sitemap
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the GitHub token in the environment
      run: |
        python sitemap-generation.py ${{ github.event.inputs.url }}

    - name: Commit and push sitemap
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is available for pushing changes
      run: |
        git add .
        git commit -m "Update sitemap for ${{ github.event.inputs.url }}"
        git push
