name: Generate Sitemap

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to generate sitemap for'
        required: true
        type: string

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git config
      run: |
        git config --global user.name 'jphabs'
        git config --global user.email 'jpbermoy@gmail.com'

    - name: Generate sitemap
      run: |
        # Add your sitemap generation command here
        # Example command: python sitemap-generation.py ${{ github.event.inputs.url }}
        echo "Generating sitemap for ${{ github.event.inputs.url }}"
        # Ensure that the sitemap file is generated or updated
        echo "<url><loc>${{ github.event.inputs.url }}</loc></url>" > sitemap.xml

    - name: Check if there are changes to commit
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit and push sitemap
      run: |
        git add .
        git diff --cached --quiet || (git commit -m "Update sitemap for ${{ github.event.inputs.url }}" && git push)