name: Generate Sitemap

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to generate sitemap for'
        required: true
        type: string

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git config
      run: |
        git config --global user.name 'jphabs'
        git config --global user.email 'jpbermoy@gmail.com'

    - name: Generate sitemap
      run: |
        echo "Generating sitemap for ${{ github.event.inputs.url }}"
        # Example: If you have a Python script for sitemap generation
        # python generate_sitemap.py "${{ github.event.inputs.url }}"

    - name: Commit and push sitemap if there are changes
      run: |
        git add .
        git diff --cached --exit-code || (git commit -m "Update sitemap for ${{ github.event.inputs.url }}" && git push)